web:
 image: nginx:latest
 ports:
    - "8080:80"
 volumes:
    - ./code:/code
    - ./site.conf:/etc/nginx/conf.d/site.conf
 links:
    - php     
php:
 image: fazrie/code:0.0.1
 # volumes:
 #    - ./code:/code
