apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    service: webapp
  namespace: default
spec:
  type: {{ .Values.service.type }}    
  selector:
    name: webapp
  ports:
  - name: web-port
    port: {{ .Values.service.port }}
    targetPort: 80
    protocol: TCP
