apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    service: webapp
    {{ .Values.tag.name }}: {{ .Values.tag.value}}      
  namespace: default
spec:
  type: {{ .Values.service.type }}    
  selector:
    name: webapp
  ports:
  - name: web-port
    port: {{ .Values.service.port }}
    targetPort: 80
    protocol: TCP
