apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "elk.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "elk.name" . }}
    helm.sh/chart: {{ include "elk.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: {{ include "elk.fullname" . }} 
  selector:
    matchLabels:
      run: elk
  template:
    metadata:
      labels:
        run: elk
    spec:
      initContainers:
      - name: fix-the-volume-permission
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - -c
          - chown -R 1000:1000 /var/lib/elasticsearch
        securityContext:
          privileged: true
        volumeMounts:
        - name: data-es
          mountPath: /var/lib/elasticsearch 
      - name: increase-the-ulimit
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sh","-c","ulimit -n 65536"]
        securityContext:
          privileged: true    
      - name: setvm-max-map-count
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true    
      containers:
      - name: elk
        image: {{ .Values.image.repository }}:{{ .Values.image.tag}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200 
          name: kibana
          protocol: TCP
        - containerPort: 5601 
          name: es
          protocol: TCP
        env:
        - name: LOGSTASH_START
          value: "0"
        - name: MAX_OPEN_FILES
          value: "65536"
        - name: MAX_MAP_COUNT
          value: "262144"  
        - name: ES_HEAP_SIZE
          value: "2g"  
        resources:
          requests:
            cpu: {{ .Values.elk.resource.cpu_req }}
            memory: {{ .Values.elk.resource.mem_req }}
          limits:
            cpu: {{ .Values.elk.resource.cpu_lim }}
            memory: {{ .Values.elk.resource.mem_lim }}
        volumeMounts:
          - name: data-es
            mountPath: /var/lib/elasticsearch 
  volumeClaimTemplates:
    - metadata:
        name: data-es
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.elk.storage.name }}
        resources:
          requests:
            storage: {{ .Values.elk.storage.size }}  
