apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    app.kubernetes.io/name: {{ include "elk.name" . }}
    helm.sh/chart: {{ include "elk.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}  
    app: elasticsearch
    type: log
spec:
  serviceName: es
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.service.selector }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.selector }}
    spec:
      terminationGracePeriodSeconds: 300      
      initContainers:
      - name: fix-the-volume-permission
        image: busybox
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - sh
          - -c
          - chown -R 1000:1000 /usr/share/elasticsearch/data
        securityContext:
          privileged: true    
        volumeMounts:
        - name: data-es
          mountPath: /usr/share/elasticsearch/data
      - name: init-sysctl
        image: busybox
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sysctl","-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-the-ulimit
        image: busybox
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sh","-c","ulimit -n 65536"]
        securityContext:
          privileged: true    
      containers:
      - name: elasticsearch
        image: {{ .Values.image.repository }}:{{ .Values.image.tag}}
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: tcp
        resources:
          requests:
            cpu: {{ .Values.elk.resource.cpu_req }}
            memory: {{ .Values.elk.resource.mem_req }}
          limits:
            cpu: {{ .Values.elk.resource.cpu_lim }}
            memory: {{ .Values.elk.resource.mem_lim }}
        env:
          - name: cluster.name
            value: elasticsearch-log-cluster
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.zen.ping.unicast.hosts
            value: "elasticsearch-cluster"      
          - name: thread_pool.bulk.queue_size
            value: "2000"
          - name: ES_JAVA_OPTS
            value: -Xms512m -Xmx512m
        volumeMounts:
          - name: data-es
            mountPath: /usr/share/elasticsearch/data      
  volumeClaimTemplates:
  - metadata:
      name: data-es
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: {{ .Values.elk.storage.name }}
      resources:
        requests:
          storage: {{ .Values.elk.storage.size }}  
