kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.elk.storage.name }}
  labels:
    app.kubernetes.io/name: {{ include "elk.name" . }}
    helm.sh/chart: {{ include "elk.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Delete