kind: ConfigMap
apiVersion: v1
metadata:
   name: elastalert
data:
  webapp_alert: |-
    name: webapps_error
    type: frequency
    index: logstash-*
    num_events: 3
    timeframe:
      minutes: 1
    filter:
    - query:
        query_string:
          query: "message: ecs-XXXXXapi AND message: level=error"
    alert:
    - "slack"
    slack:
    slack_webhook_url: "https://hooks.slack.com/services/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    slack_emoji_override: ":robot_face:"
    slack_msg_color: "warning"
    alert_text: "You can check the alert dashboard on Kibana"
    alert_subject: "Elastalert event: More than 3 request with level ERROR has been detected in the last minute."
    alert_text_type: exclude_fields
  500_alert: |-
    name: 500_error
    type: frequency
    index: logstash-*
    num_events: 3
    timeframe:
      minutes: 1
    filter:
    - query:
        query_string:
          query: "message: ecs-XXXXu-api AND message: level=error"
    alert:
    - "slack"
    slack:
    slack_webhook_url: "https://hooks.slack.com/services/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    slack_emoji_override: ":robot_face:"
    slack_msg_color: "warning"
    alert_text: "You can check the alert dashboard on Kibana:" 
    alert_subject: "Elastalert event: More than 3 request with level ERROR has been detected in the last minute."
    alert_text_type: exclude_fields
