apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    service: webapp
  namespace: default
spec:
  type: LoadBalancer
  selector:
    name: webapp
  ports:
  - name: web-port
    port: 80
    targetPort: 80
    protocol: TCP
