apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: hpa-webapp
  namespace: default
  labels:
    sre_candidate: setyadi
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 85

    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 85
